triggers:
- envs: []
  last_enabled_at: 2024-04-01 10:46:05.731281
  name: run_once_a_month
  pipeline_uuid: nyt_api_to_gcs_and_bigquery
  schedule_interval: '@monthly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-30 23:55:00
  status: active
  variables: {}
- envs: []
  last_enabled_at: null
  name: Backfill backfill_2000_2022
  pipeline_uuid: nyt_api_to_gcs_and_bigquery
  schedule_interval: '@once'
  schedule_type: null
  settings:
    pipeline_run_limit: '1'
  sla: null
  start_time: 2024-04-02 09:35:31.296003
  status: inactive
  variables: {}
