FROM python:3.10

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /nyt_pipeline/requirements.txt

WORKDIR /nyt_pipeline

RUN pip install --upgrade pip
RUN python -m pip install -r requirements.txt --root-user-action=ignore

COPY . /nyt_pipeline

CMD ["/bin/bash"]
