version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start nyt-etl-pipeline
    env_file:
      - ~/.env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/nyt-etl-pipeline
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ~/nyt_project.json:/home/src/personal-gcp.json
      - ~/.env:/home/src/.env
    restart: on-failure:5